In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [1]:
np.arange(4)

NameError: name 'np' is not defined

In [6]:
 np.arange(5) # easy way for writing array we only give integer to which we want the array elements

array([0, 1, 2, 3, 4])

In [7]:
np.zeros(4) # gives us an array of zeros

array([0., 0., 0., 0.])

In [8]:
np.ones(8)  # gives us an array of ones

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.empty(7)  # gives us empty array also can have garbage values, its different from zeros

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
a.dtype  # for finding dtype or type of any array elements

dtype('int32')

In [12]:
b = np.array([[1,1,1], [2,3,4], [55,566,3554354]])# for writing multidimensional array we keep them all in main square bracket.

In [13]:
b

array([[      1,       1,       1],
       [      2,       3,       4],
       [     55,     566, 3554354]])

In [17]:
b.shape # tells us about the array its rows and columns

(3, 3)

In [18]:
b.dtype

dtype('int32')