In [1]:
import numpy as np

In [2]:
a = np.array([23,45,66,28,14,30,8,99])  # for writing an array

In [3]:
a

array([23, 45, 66, 28, 14, 30,  8, 99])

In [4]:
b = a[2:6]  # for slicing an array if we slice simply like this and make changes like in next step then we change parent array,

In [5]:
b[0]= 4

In [6]:
a  # that's why we take copy during slicing of parent array so that it will not affect parent when we make changes 

array([23, 45,  4, 28, 14, 30,  8, 99])

In [7]:
c = np.array([34,65,6,234,324,23,2,56])

In [8]:
d = c[3:7].copy() # if we write our slice part of array like this then if we made change it will not affect parent

In [9]:
d[2]= 0 # will only affect d var

In [10]:
d # changes are only in d

array([234, 324,   0,   2])

In [11]:
c # it is not affected by changes in d

array([ 34,  65,   6, 234, 324,  23,   2,  56])

In [12]:
c.sort() # for sorting the array in increasing format

In [13]:
c

array([  2,   6,  23,  34,  56,  65, 234, 324])

In [14]:
arr = np.array([[11,21,3],[41,53,6], [17,28,9]])

In [15]:
arr

array([[11, 21,  3],
       [41, 53,  6],
       [17, 28,  9]])

In [16]:
arr.sort(axis=0) # for sorting the array in axis. Axis 0 is used for cols and Axis 1 used for rows.

In [17]:
arr

array([[11, 21,  3],
       [17, 28,  6],
       [41, 53,  9]])

In [18]:
arr.sort(axis=1)

In [19]:
arr

array([[ 3, 11, 21],
       [ 6, 17, 28],
       [ 9, 41, 53]])

In [20]:
arr1 = np.array([1,2,3])

In [21]:
arr2 = np.array([4,5,6])

In [22]:
np.dot(arr1,arr2)  # gives us dot product if we get error sometimes for multidimensional its bcs of there transpose

32

In [23]:
np.cross(arr1,arr2)  # for cross product

array([-3,  6, -3])

In [24]:
arr4 = np.array([[12,53,40], [40,243,23]])

In [25]:
%time np.dot(arr, arr4.transpose())

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 1459,  3276],
       [ 2093,  5015],
       [ 4401, 11542]])

In [26]:
arr4.sort(kind= "heapsort")

In [27]:
arr4

array([[ 12,  40,  53],
       [ 23,  40, 243]])

In [28]:
arr5 = np.array([1,5434,64,3,6,2,6,77,8,2,4,34,645,1])

In [29]:
arr5.argsort()  # will tells us how elements are showing mean there index will be given

array([ 0, 13,  5,  9,  3, 10,  4,  6,  8, 11,  2,  7, 12,  1],
      dtype=int64)

In [30]:
arr5.argmax()  # will gives us index of max element

1

In [31]:
arr5.argmin()  # will gives us index of min element

0

In [32]:
arr5.shape

(14,)

In [33]:
array = arr5.reshape(7,2)  # will reshape the array in given rows and cols

In [34]:
array

array([[   1, 5434],
       [  64,    3],
       [   6,    2],
       [   6,   77],
       [   8,    2],
       [   4,   34],
       [ 645,    1]])

In [35]:
array.argsort(axis=0)

array([[0, 6],
       [5, 2],
       [2, 4],
       [3, 1],
       [4, 5],
       [1, 3],
       [6, 0]], dtype=int64)