In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a[1,2]

6

In [4]:
a[1,1]

5

In [5]:
a[0,2]

3

In [6]:
a[0,1] = 9

In [7]:
a

array([[1, 9, 3],
       [4, 5, 6]])

In [8]:
a[1: 0,2]

array([], dtype=int32)

In [9]:
a.shape

(2, 3)

In [108]:
np.zeros((4,4),np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [106]:
ar = np.arange(4)
ar

array([0, 1, 2, 3])

In [12]:
ar.reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [113]:
np.full((4,5),99)

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [114]:
# to get any element array not ones or zeros
np.full_like(a, 9)

array([[9, 9, 9],
       [9, 9, 9]])

In [123]:
# for creating any random number arrays
np.random.rand(4,4)

array([[0.59979223, 0.59240448, 0.32893855, 0.59250417],
       [0.96641125, 0.94039171, 0.50125398, 0.91053067],
       [0.16558379, 0.57899828, 0.66653981, 0.87890022],
       [0.65887095, 0.51361769, 0.60400166, 0.98354797]])

In [125]:
 # will generate random numbers and make them into array of our own choice
np.random.randint(2,8, size = (3,2)) 

array([[7, 4],
       [5, 3],
       [7, 6]])

In [129]:
rpt = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [134]:
# for repeating an array
np.repeat(rpt,4, axis=0) 

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

# stacking array into arrays

In [166]:
stk = np.array([[1,2,4]])

In [167]:
stk2 = np.array([[4,34,99]])

In [171]:
 # for vertically stacking
np.vstack((stk2,stk))

array([[ 4, 34, 99],
       [ 1,  2,  4]])

In [172]:
 # for horizontally stacking
np.hstack((stk,stk2)) 

array([[ 1,  2,  4,  4, 34, 99]])

In [13]:
lin = np.linspace(1,100,50)
lin

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [14]:
lin1 =lin.reshape(5,10)
lin1

array([[  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347],
       [ 21.20408163,  23.2244898 ,  25.24489796,  27.26530612,
         29.28571429,  31.30612245,  33.32653061,  35.34693878,
         37.36734694,  39.3877551 ],
       [ 41.40816327,  43.42857143,  45.44897959,  47.46938776,
         49.48979592,  51.51020408,  53.53061224,  55.55102041,
         57.57142857,  59.59183673],
       [ 61.6122449 ,  63.63265306,  65.65306122,  67.67346939,
         69.69387755,  71.71428571,  73.73469388,  75.75510204,
         77.7755102 ,  79.79591837],
       [ 81.81632653,  83.83673469,  85.85714286,  87.87755102,
         89.89795918,  91.91836735,  93.93877551,  95.95918367,
         97.97959184, 100.        ]])

In [15]:
lin1[2,0]= 3

In [16]:
lin1

array([[  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347],
       [ 21.20408163,  23.2244898 ,  25.24489796,  27.26530612,
         29.28571429,  31.30612245,  33.32653061,  35.34693878,
         37.36734694,  39.3877551 ],
       [  3.        ,  43.42857143,  45.44897959,  47.46938776,
         49.48979592,  51.51020408,  53.53061224,  55.55102041,
         57.57142857,  59.59183673],
       [ 61.6122449 ,  63.63265306,  65.65306122,  67.67346939,
         69.69387755,  71.71428571,  73.73469388,  75.75510204,
         77.7755102 ,  79.79591837],
       [ 81.81632653,  83.83673469,  85.85714286,  87.87755102,
         89.89795918,  91.91836735,  93.93877551,  95.95918367,
         97.97959184, 100.        ]])

In [17]:
np.empty((2,3), np.int32)

array([[-1418120912,         581,           0],
       [          0,      131074,  1851859059]])

In [109]:
np.empty_like(a) # we can use like with any array in same way like zeros_like, ones_like, full_like

array([[ 824188960, 1629504557, 2036429426],
       [ 543584032, 1717923683, 1768122726]])

In [19]:
identity = np.identity(45, np.int32)
identity

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [20]:
identity[44,2] = 10

In [21]:
identity

array([[ 1,  0,  0, ...,  0,  0,  0],
       [ 0,  1,  0, ...,  0,  0,  0],
       [ 0,  0,  1, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  1,  0,  0],
       [ 0,  0,  0, ...,  0,  1,  0],
       [ 0,  0, 10, ...,  0,  0,  1]])

In [22]:
identity[3:9]

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]])

In [23]:
lin1.ravel()  # will change into its original form

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
         3.        ,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

# numpy for axis

In [24]:
arr1 = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr1.sum(axis=0)  # will take sum of numbers column vise

array([12, 15, 18])

In [26]:
arr1.sum(axis=1) # will take sum row vise

array([ 6, 15, 24])

In [27]:
arr1.T # will take trnaspose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
for item in arr1.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [29]:
arr1.ndim

2

In [30]:
arr1.nbytes

36

In [31]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2 = np.array([[4,5,6], [3,2,1], [9,8,7]])
arr2

array([[4, 5, 6],
       [3, 2, 1],
       [9, 8, 7]])

In [33]:
arr1+arr2

array([[ 5,  7,  9],
       [ 7,  7,  7],
       [16, 16, 16]])

In [34]:
arr1+arr2

array([[ 5,  7,  9],
       [ 7,  7,  7],
       [16, 16, 16]])

In [35]:
arr1*arr2

array([[ 4, 10, 18],
       [12, 10,  6],
       [63, 64, 63]])

In [36]:
arr1/arr2

array([[0.25      , 0.4       , 0.5       ],
       [1.33333333, 2.5       , 6.        ],
       [0.77777778, 1.        , 1.28571429]])

In [37]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [38]:
arr3 = ([[1, 2, 0],[7, 0, 9], [4, 0, 6]])
arr3

[[1, 2, 0], [7, 0, 9], [4, 0, 6]]

In [39]:
np.where(arr1>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [42]:
np.nonzero(arr3)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 0, 2, 0, 2], dtype=int64))

### Advanced indexing

In [95]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
arr1[1,:]  # for getting single row from data

array([4, 5, 6])

In [58]:
arr1[:,2]  # for getting the whole column

array([3, 6, 9])

In [64]:
arr  = np.array([[1,2,4,5,6,7,0,21,43,56],[4,6,8,9,4,3,1,81,34,99]])
arr

array([[ 1,  2,  4,  5,  6,  7,  0, 21, 43, 56],
       [ 4,  6,  8,  9,  4,  3,  1, 81, 34, 99]])

In [67]:
arr[1,3:9] # will start from row index_1 and column index_3 and goes all the way to 9th index in row

array([ 9,  4,  3,  1, 81, 34])

In [70]:
arr[0,2:10:3]  # will jump one index last index number point to jumping 


array([ 4,  7, 43])

In [73]:
arr[:, 3] = [14,15] # will change the whole or column or row whose indexing we are using

In [72]:
arr

array([[ 1,  2,  4, 14,  6,  7,  0, 21, 43, 56],
       [ 4,  6,  8, 15,  4,  3,  1, 81, 34, 99]])

In [84]:
arr

array([[ 1,  2,  4, 14,  6,  7,  0, 21, 43, 56],
       [ 4,  6,  8, 15,  4,  3,  1, 81, 34, 99]])

In [101]:
arr[1:,]

array([[ 4,  6,  8, 15,  4,  3,  1, 81, 34, 99]])

In [102]:
arr.T

array([[ 1,  4],
       [ 2,  6],
       [ 4,  8],
       [14, 15],
       [ 6,  4],
       [ 7,  3],
       [ 0,  1],
       [21, 81],
       [43, 34],
       [56, 99]])